version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mounting default.conf here
      - ./:/var/www/html # Application files

    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - datas

  php-fpm:
    image: php:8.3-fpm
    volumes:
      - ./:/var/www/html # Application files
    depends_on:
      - datas

  datas:
    image: mysql:latest

    container_name: datas
    environment:

      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii2basic
      MYSQL_PASSWORD: yii2basic
      MYSQL_ROOT_PASSWORD: yii2basic

    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: datas

      MYSQL_PASSWORD: yii2basic
      MYSQL_ROOT_PASSWORD: yii2basic

    ports:
      - "8080:80"
    depends_on:
      - datas

volumes:
  db_data:
